Name              = "koding"
Enabled           = true
Users             = ["ankara", "istanbul"]
Interval 	      = 10000000000
id       	      = 1234567891
Labels       	  = [123,456]

[Postgres]
Enabled           = true
Port              = 5432
Hosts             = ["192.168.2.1", "192.168.2.2", "192.168.2.3"]
AvailabilityRatio = 8.23
